### ISSUE TITLE
MYSQL MIGRATION EPIC - Dates updated per change request (was 2/13 - 5/26)

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#38]
DEV
- [x] libmysqldev1	digitizedbooks 
- [x] libmysqldev1	eulindexer     
- [x] libmysqldev1	fedora38_qas (decommission should have been in August)      
- [x] libmysqldev1	findingaids   (decommission should have been in August)
- [x] libmysqldev1 keep (test)
- [x] libmysqldev1 library_information (decommissioned)
- [x] libmysqldev1 oai38_qas (decommissioned)
- [x] libmysqldev1 openemory (test)
- [x] libmysqldev1	pidman  (ready for decommission)
- [x] libmysqldev1	pidqas (migrated as pidman_dev)
- [x] libmysqldev1	rushdie (decommissioned - moved to sqlite)

PROD 
- [x] libmysqlprod1	digitizedbooks
- [x] libmysqlprod1	emoryit (decommissioned)
- [x] libmysqlprod1	emorylib
- [x] libmysqlprod1	emorylits (decommissioned)
- [x] libmysqlprod1	etd (decommissioned)
- [x] libmysqlprod1	eulindexer
- [x] libmysqlprod1	findingaids   (to decommission)
- [x] libmysqlprod1	keep

- [x] libmysqlprod1	libraryuse (decommissioned)
- [x] libmysqlprod1	marbla (decommissioned)
- [x] libmysqlprod1	openemory
- [x] libmysqlprod1	pidman
- [x] libmysqlprod1	rushdie (decommissioned - moved to sqlite)

**Comment by libdgg** [comment]
ACTION: confirm naming conventions are in scope

**Comment by libdgg** [comment]
COMPLETED: Change request to pause on the mysql migration phase with the only exception being the mysql for openemory which will be managed under the OE23 project. This group and board will be dormant until we resart this effort after OE23 work has been addressed, estimated to be in June so we can restart on or before July. 
Change Request approved 2023-03-17

https://emory.sharepoint.com/:w:/r/sites/EULLTDS/_layouts/15/Doc.aspx?sourcedoc=%7BF5B1684E-C317-46E2-96A1-F98464400F35%7D&file=LEGACY_DATABASE_MIGRATION_CHANGE_REQUEST%202023-03-08.docx&action=default&mobileredirect=true&CID=943c7002-a695-801a-d109-a81a3ee8ad45
